# Generated by Django 2.2.1 on 2019-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default='static/ikona.png', upload_to='static'),
        ),
    ]
